/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/alert/': RouteRecordInfo<'/alert/', '/alert', Record<never, never>, Record<never, never>>,
    '/alerts/': RouteRecordInfo<'/alerts/', '/alerts', Record<never, never>, Record<never, never>>,
    '/alerts/[id]': RouteRecordInfo<'/alerts/[id]', '/alerts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/alerts/new': RouteRecordInfo<'/alerts/new', '/alerts/new', Record<never, never>, Record<never, never>>,
    '/incident/': RouteRecordInfo<'/incident/', '/incident', Record<never, never>, Record<never, never>>,
    '/incident/[id]': RouteRecordInfo<'/incident/[id]', '/incident/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/incidents/': RouteRecordInfo<'/incidents/', '/incidents', Record<never, never>, Record<never, never>>,
    '/incidents/[id]': RouteRecordInfo<'/incidents/[id]', '/incidents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/incidents/new': RouteRecordInfo<'/incidents/new', '/incidents/new', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/permissions/demo': RouteRecordInfo<'/permissions/demo', '/permissions/demo', Record<never, never>, Record<never, never>>,
    '/service/': RouteRecordInfo<'/service/', '/service', Record<never, never>, Record<never, never>>,
    '/service/[id]': RouteRecordInfo<'/service/[id]', '/service/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/test/editor': RouteRecordInfo<'/test/editor', '/test/editor', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
  }
}
