packages:
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
ignoredBuiltDependencies:
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - msgpackr-extract
