/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * API - version 1.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'auth.login': ['POST', '/auth/login'],
  'alert.receive': ['POST', '/alert'],
  'alert.receiveWithServiceId': ['POST', '/alert/{serviceId}']
};
