/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 *  - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'service.create': ['POST', '/api/service'],
  'service.findAll': ['GET', '/api/service'],
  'service.findOne': ['GET', '/api/service/{id}'],
  'service.update': ['PATCH', '/api/service/{id}'],
  'alert.findAll': ['GET', '/api/alert'],
  'incident.findAll': ['GET', '/api/incident'],
  'incident.findOne': ['GET', '/api/incident/{id}'],
  'incident.update': ['PATCH', '/api/incident/{id}'],
  'incidenttype.create': ['POST', '/api/incident-type/{serviceId}'],
  'incidenttype.findAll': ['GET', '/api/incident-type/{serviceId}'],
  'incidenttype.findOne': ['GET', '/api/incident-type/{serviceId}/{id}'],
  'incidenttype.update': ['PATCH', '/api/incident-type/{serviceId}/{id}'],
  'incidenttype.remove': ['DELETE', '/api/incident-type/{serviceId}/{id}'],
  'serviceroute.create': ['POST', '/api/service-route'],
  'serviceroute.findAll': ['GET', '/api/service-route'],
  'serviceroute.findOne': ['GET', '/api/service-route/{id}'],
  'serviceroute.update': ['PATCH', '/api/service-route/{id}'],
  'serviceroute.remove': ['DELETE', '/api/service-route/{id}'],
  'globalcustomfield.create': ['POST', '/api/global-custom-field'],
  'globalcustomfield.findAll': ['GET', '/api/global-custom-field'],
  'globalcustomfield.findOne': ['GET', '/api/global-custom-field/{id}'],
  'globalcustomfield.update': ['PATCH', '/api/global-custom-field/{id}'],
  'globalcustomfield.remove': ['DELETE', '/api/global-custom-field/{id}']
};
