/* tslint:disable */
/* eslint-disable */
/**
 *  - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type CreateServiceDto = {
  /**
   * [required]
   */
  name: string;
  description?: string;
};
export type AlertDto = {
  /**
   * [required]
   */
  id: number;
  /**
   * [required]
   */
  title: string;
  /**
   * [required]
   */
  content: string;
  /**
   * [required]
   */
  customFields: object | null;
  /**
   * [required]
   */
  serviceId: number;
  /**
   * [required]
   */
  incidentId: number | null;
  /**
   * [required]
   */
  createdAt: string;
  /**
   * [required]
   */
  updatedAt: string;
};
export type AlertResponseDto = {
  /**
   * [required]
   */
  data: AlertDto[];
  /**
   * [required]
   */
  total: number;
  /**
   * [required]
   */
  page: number;
  /**
   * [required]
   */
  pageSize: number;
};
export type CreateIncidentDto = object;
export type UpdateIncidentDto = object;
export type CreateIncidentTypeDto = object;
export type UpdateIncidentTypeDto = object;
export type CreateServiceRouteDto = object;
export type UpdateServiceRouteDto = object;
export type CreateGlobalCustomFieldDto = object;
export type UpdateGlobalCustomFieldDto = object;
declare global {
  interface Apis {
    service: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/service
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // [required]
       *   name: string
       *   description?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      create<
        Config extends Alova2MethodConfig<unknown> & {
          data: CreateServiceDto;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'service.create', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/service
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      findAll<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'service.findAll', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/service/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      findOne<
        Config extends Alova2MethodConfig<object> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'service.findOne', Config>;
      /**
       * ---
       *
       * [PATCH]
       *
       * **path:** /api/service/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // [required]
       *   name: string
       *   description?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      update<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: CreateServiceDto;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'service.update', Config>;
    };
    alert: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/alert
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   pageSize: number
       *   // [required]
       *   page: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   data: Array<{
       *     // [required]
       *     id: number
       *     // [required]
       *     title: string
       *     // [required]
       *     content: string
       *     // [required]
       *     customFields: object | null
       *     // [required]
       *     serviceId: number
       *     // [required]
       *     incidentId: number | null
       *     // [required]
       *     createdAt: string
       *     // [required]
       *     updatedAt: string
       *   }>
       *   // [required]
       *   total: number
       *   // [required]
       *   page: number
       *   // [required]
       *   pageSize: number
       * }
       * ```
       */
      findAll<
        Config extends Alova2MethodConfig<AlertResponseDto> & {
          params: {
            /**
             * [required]
             */
            pageSize: number;
            /**
             * [required]
             */
            page: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<AlertResponseDto, 'alert.findAll', Config>;
    };
    incident: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/incident
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      create<
        Config extends Alova2MethodConfig<string> & {
          data: CreateIncidentDto;
        }
      >(
        config: Config
      ): Alova2Method<string, 'incident.create', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/incident
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      findAll<Config extends Alova2MethodConfig<string>>(
        config?: Config
      ): Alova2Method<string, 'incident.findAll', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/incident/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      findOne<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string, 'incident.findOne', Config>;
      /**
       * ---
       *
       * [PATCH]
       *
       * **path:** /api/incident/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      update<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: UpdateIncidentDto;
        }
      >(
        config: Config
      ): Alova2Method<string, 'incident.update', Config>;
    };
    incidenttype: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/incident-type/{serviceId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   serviceId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      create<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            serviceId: string;
          };
          data: CreateIncidentTypeDto;
        }
      >(
        config: Config
      ): Alova2Method<string, 'incidenttype.create', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/incident-type/{serviceId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   serviceId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      findAll<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            serviceId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string, 'incidenttype.findAll', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/incident-type/{serviceId}/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   serviceId: string
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      findOne<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            serviceId: string;
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string, 'incidenttype.findOne', Config>;
      /**
       * ---
       *
       * [PATCH]
       *
       * **path:** /api/incident-type/{serviceId}/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   serviceId: string
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      update<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            serviceId: string;
            /**
             * [required]
             */
            id: string;
          };
          data: UpdateIncidentTypeDto;
        }
      >(
        config: Config
      ): Alova2Method<string, 'incidenttype.update', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/incident-type/{serviceId}/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   serviceId: string
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      remove<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            serviceId: string;
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string, 'incidenttype.remove', Config>;
    };
    serviceroute: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/service-route
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      create<
        Config extends Alova2MethodConfig<string> & {
          data: CreateServiceRouteDto;
        }
      >(
        config: Config
      ): Alova2Method<string, 'serviceroute.create', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/service-route
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      findAll<Config extends Alova2MethodConfig<string>>(
        config?: Config
      ): Alova2Method<string, 'serviceroute.findAll', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/service-route/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      findOne<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string, 'serviceroute.findOne', Config>;
      /**
       * ---
       *
       * [PATCH]
       *
       * **path:** /api/service-route/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      update<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: UpdateServiceRouteDto;
        }
      >(
        config: Config
      ): Alova2Method<string, 'serviceroute.update', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/service-route/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      remove<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string, 'serviceroute.remove', Config>;
    };
    globalcustomfield: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/global-custom-field
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      create<
        Config extends Alova2MethodConfig<string> & {
          data: CreateGlobalCustomFieldDto;
        }
      >(
        config: Config
      ): Alova2Method<string, 'globalcustomfield.create', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/global-custom-field
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      findAll<Config extends Alova2MethodConfig<string>>(
        config?: Config
      ): Alova2Method<string, 'globalcustomfield.findAll', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/global-custom-field/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      findOne<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string, 'globalcustomfield.findOne', Config>;
      /**
       * ---
       *
       * [PATCH]
       *
       * **path:** /api/global-custom-field/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      update<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: UpdateGlobalCustomFieldDto;
        }
      >(
        config: Config
      ): Alova2Method<string, 'globalcustomfield.update', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/global-custom-field/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      remove<
        Config extends Alova2MethodConfig<string> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string, 'globalcustomfield.remove', Config>;
    };
  }

  var Apis: Apis;
}
