/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Elysia Documentation - version 0.0.0
 *
 * Development documentation
 *
 * OpenAPI version: 3.0.3
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.getApiService': ['GET', '/api/service/'],
  'general.postApiService': ['POST', '/api/service/'],
  'general.getApiServiceById': ['GET', '/api/service/{id}'],
  'general.patchApiServiceById': ['PATCH', '/api/service/{id}'],
  'general.getapiserviceRoute': ['GET', '/api/service-route/'],
  'general.postapiserviceRoute': ['POST', '/api/service-route/'],
  'general.getapiserviceRoutebyid': ['GET', '/api/service-route/{id}'],
  'general.patchapiserviceRoutebyid': ['PATCH', '/api/service-route/{id}'],
  'general.deleteapiserviceRoutebyid': ['DELETE', '/api/service-route/{id}'],
  'general.getapiserviceCustomFields': ['GET', '/api/service-custom-fields/'],
  'general.postapiserviceCustomFields': ['POST', '/api/service-custom-fields/'],
  'general.getapiserviceCustomFieldsbyid': ['GET', '/api/service-custom-fields/{id}'],
  'general.patchapiserviceCustomFieldsbyid': ['PATCH', '/api/service-custom-fields/{id}'],
  'general.deleteapiserviceCustomFieldsbyid': ['DELETE', '/api/service-custom-fields/{id}'],
  'general.getApiIncident': ['GET', '/api/incident/'],
  'general.getapiincidentTypes': ['GET', '/api/incident-types/'],
  'general.postapiincidentTypes': ['POST', '/api/incident-types/'],
  'general.getapiincidentTypesbyid': ['GET', '/api/incident-types/{id}'],
  'general.patchapiincidentTypesbyid': ['PATCH', '/api/incident-types/{id}'],
  'general.deleteapiincidentTypesbyid': ['DELETE', '/api/incident-types/{id}'],
  'general.postApiAlert': ['POST', '/api/alert/'],
  'general.getApiAlert': ['GET', '/api/alert/'],
  'general.postApiAlertByServiceId': ['POST', '/api/alert/{serviceId}'],
  'general.getapiglobalCustomFields': ['GET', '/api/global-custom-fields/'],
  'general.postapiglobalCustomFields': ['POST', '/api/global-custom-fields/'],
  'general.getapiglobalCustomFieldsbyid': ['GET', '/api/global-custom-fields/{id}'],
  'general.patchapiglobalCustomFieldsbyid': ['PATCH', '/api/global-custom-fields/{id}'],
  'general.deleteapiglobalCustomFieldsbyid': ['DELETE', '/api/global-custom-fields/{id}']
};
